"""add_currency_and_statement_month_fields

Revision ID: 0c994013af9d
Revises: 4bb91fa63fd5
Create Date: 2025-06-05 20:12:44.773812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c994013af9d'
down_revision: Union[str, None] = '4bb91fa63fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('statement_month', sa.Date(), nullable=True))
    op.add_column('statements', sa.Column('ai_insights', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('currency', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'currency')
    op.drop_column('statements', 'ai_insights')
    op.drop_column('statements', 'statement_month')
    # ### end Alembic commands ###
