"""update_default_categories_to_5_fixed

Revision ID: 3e3dbc9b11f5
Revises: waitlist_fields
Create Date: 2025-08-17 19:07:38.577251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3dbc9b11f5'
down_revision: Union[str, None] = 'waitlist_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_excluded_keywords_keyword_normalized'), 'user_excluded_keywords', ['keyword_normalized'], unique=False)
    op.create_index(op.f('ix_user_excluded_keywords_user_id'), 'user_excluded_keywords', ['user_id'], unique=False)
    
    # Create the enum type first
    user_type_enum = sa.Enum('free', 'plus', 'pro', 'admin', name='usertypeenum')
    user_type_enum.create(op.get_bind(), checkfirst=True)
    
    # Drop the existing default, change the type, then set the new default
    op.execute("ALTER TABLE users ALTER COLUMN plan_tier DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN plan_tier TYPE usertypeenum USING plan_tier::usertypeenum")
    op.execute("ALTER TABLE users ALTER COLUMN plan_tier SET DEFAULT 'free'::usertypeenum")
    op.alter_column('users', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'plan_tier',
               existing_type=sa.Enum('free', 'plus', 'pro', 'admin', name='usertypeenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    
    # Drop the enum type
    sa.Enum(name='usertypeenum').drop(op.get_bind(), checkfirst=True)
    
    op.drop_index(op.f('ix_user_excluded_keywords_user_id'), table_name='user_excluded_keywords')
    op.drop_index(op.f('ix_user_excluded_keywords_keyword_normalized'), table_name='user_excluded_keywords')
    # ### end Alembic commands ###
