"""add_alerts_table

Revision ID: 51336fa53cb6
Revises: 0c994013af9d
Create Date: 2025-06-07 12:17:57.677175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import GUID type and enums to match models
from app.core.types import GUID
from app.models.alert import AlertType, AlertSeverity


# revision identifiers, used by Alembic.
revision: str = '51336fa53cb6'
down_revision: Union[str, None] = '0c994013af9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'alerts',
        sa.Column('id', GUID(), nullable=False),
        sa.Column('user_id', GUID(), nullable=False),
        sa.Column('statement_id', GUID(), nullable=True),
        sa.Column('alert_type', sa.Enum(AlertType, name='alerttype'), nullable=False),
        sa.Column('severity', sa.Enum(AlertSeverity, name='alertseverity'), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['statement_id'], ['statements.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # No need for an index on id; it's already the PK
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # Drop enums if needed (optional, left to default behavior)
    # ### end Alembic commands ###
