"""add_async_processing_fields_to_statements

Revision ID: ca26460dbd46
Revises: f83d2a1b9c54
Create Date: 2025-06-07 20:11:43.163074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca26460dbd46'
down_revision: Union[str, None] = 'f83d2a1b9c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('statements', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('statements', sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'processing_completed_at')
    op.drop_column('statements', 'processing_started_at')
    op.drop_column('statements', 'error_message')
    # ### end Alembic commands ###
