"""enhance_user_profile_and_settings

Revision ID: f83d2a1b9c54
Revises: 51336fa53cb6
Create Date: 2025-06-07 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83d2a1b9c54'
down_revision: Union[str, None] = '51336fa53cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to users table
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    
    # Add preference columns
    op.add_column('users', sa.Column('preferred_currency', sa.Enum('USD', 'PEN', 'EUR', 'GBP', name='currencyenum'), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.Enum('UTC_MINUS_8', 'UTC_MINUS_7', 'UTC_MINUS_6', 'UTC_MINUS_5', 'UTC_MINUS_3', 'UTC_0', 'UTC_PLUS_1', name='timezoneenum'), nullable=True))
    
    # Add notification preference columns
    op.add_column('users', sa.Column('budget_alerts_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('payment_reminders_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('transaction_alerts_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('weekly_summary_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('monthly_reports_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('push_notifications_enabled', sa.Boolean(), nullable=True))
    
    # Set default values for existing users
    op.execute("UPDATE users SET preferred_currency = 'USD' WHERE preferred_currency IS NULL")
    op.execute("UPDATE users SET timezone = 'UTC_MINUS_8' WHERE timezone IS NULL")
    op.execute("UPDATE users SET budget_alerts_enabled = true WHERE budget_alerts_enabled IS NULL")
    op.execute("UPDATE users SET payment_reminders_enabled = true WHERE payment_reminders_enabled IS NULL")
    op.execute("UPDATE users SET transaction_alerts_enabled = false WHERE transaction_alerts_enabled IS NULL")
    op.execute("UPDATE users SET weekly_summary_enabled = true WHERE weekly_summary_enabled IS NULL")
    op.execute("UPDATE users SET monthly_reports_enabled = true WHERE monthly_reports_enabled IS NULL")
    op.execute("UPDATE users SET email_notifications_enabled = true WHERE email_notifications_enabled IS NULL")
    op.execute("UPDATE users SET push_notifications_enabled = false WHERE push_notifications_enabled IS NULL")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_notifications_enabled')
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_column('users', 'monthly_reports_enabled')
    op.drop_column('users', 'weekly_summary_enabled')
    op.drop_column('users', 'transaction_alerts_enabled')
    op.drop_column('users', 'payment_reminders_enabled')
    op.drop_column('users', 'budget_alerts_enabled')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'preferred_currency')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
