"""add_category_keywords_table_with_guid

Revision ID: f8bc87e74a05
Revises: 7dc00e0d485a
Create Date: 2025-06-13 15:08:28.187758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import GUID


# revision identifiers, used by Alembic.
revision: str = 'f8bc87e74a05'
down_revision: Union[str, None] = '7dc00e0d485a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_keywords',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('category_id', GUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alerts', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('alerts', sa.Column('criteria', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('threshold', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('frequency', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('alerts', 'id',
               existing_type=sa.INTEGER(),
               type_=app.core.types.GUID(),
               existing_nullable=False)
    op.alter_column('alerts', 'user_id',
               existing_type=sa.INTEGER(),
               type_=app.core.types.GUID(),
               existing_nullable=False)
    op.alter_column('alerts', 'statement_id',
               existing_type=sa.INTEGER(),
               type_=app.core.types.GUID(),
               existing_nullable=True)
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.VARCHAR(length=23),
               type_=sa.Enum('SPENDING_LIMIT', 'MERCHANT_WATCH', 'CATEGORY_BUDGET', 'UNUSUAL_SPENDING', 'LARGE_TRANSACTION', 'NEW_MERCHANT', 'BUDGET_EXCEEDED', name='alerttype'),
               existing_nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='alertseverity'),
               existing_nullable=False)
    op.drop_index('ix_alerts_id', table_name='alerts')
    op.drop_column('alerts', 'message')
    op.alter_column('categories', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('categories', 'keywords')
    op.drop_column('statements', 'retry_count')
    op.alter_column('transactions', 'statement_id',
               existing_type=sa.TEXT(),
               type_=app.core.types.GUID(),
               existing_nullable=True)
    op.drop_index('idx_transactions_statement_id', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_transactions_statement_id', 'transactions', ['statement_id'], unique=False)
    op.alter_column('transactions', 'statement_id',
               existing_type=app.core.types.GUID(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('statements', sa.Column('retry_count', sa.VARCHAR(), nullable=True))
    op.add_column('categories', sa.Column('keywords', sa.TEXT(), nullable=True))
    op.alter_column('categories', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('alerts', sa.Column('message', sa.TEXT(), nullable=False))
    op.create_index('ix_alerts_id', 'alerts', ['id'], unique=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='alertseverity'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('alerts', 'alert_type',
               existing_type=sa.Enum('SPENDING_LIMIT', 'MERCHANT_WATCH', 'CATEGORY_BUDGET', 'UNUSUAL_SPENDING', 'LARGE_TRANSACTION', 'NEW_MERCHANT', 'BUDGET_EXCEEDED', name='alerttype'),
               type_=sa.VARCHAR(length=23),
               existing_nullable=False)
    op.alter_column('alerts', 'statement_id',
               existing_type=app.core.types.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('alerts', 'user_id',
               existing_type=app.core.types.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('alerts', 'id',
               existing_type=app.core.types.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'triggered_at')
    op.drop_column('alerts', 'is_active')
    op.drop_column('alerts', 'frequency')
    op.drop_column('alerts', 'threshold')
    op.drop_column('alerts', 'criteria')
    op.drop_column('alerts', 'description')
    op.drop_table('category_keywords')
    # ### end Alembic commands ###
