
name: Deploy Celery Worker to Render

on:
  push:
    branches: [ master ]
    paths:
      - "app/celery/**"
      - "requirements.txt"
      - "Dockerfile.celery"
      - ".github/workflows/deploy-celery-worker.yml"
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you deploying manually?"
        required: false
        default: ""

permissions:
  contents: read

concurrency:
  group: render-celery-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Trigger Render deploy hook (celery)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Ensure deploy hook secret is set
        env:
          RENDER_CELERY_DEPLOY_HOOK: ${{ secrets.RENDER_CELERY_DEPLOY_HOOK }}
        run: |
          set -euo pipefail
          if [ -z "${RENDER_CELERY_DEPLOY_HOOK:-}" ]; then
            echo "RENDER_CELERY_DEPLOY_HOOK secret is not set" >&2
            exit 1
          fi

      - name: Trigger Render deploy hook
        env:
          RENDER_CELERY_DEPLOY_HOOK: ${{ secrets.RENDER_CELERY_DEPLOY_HOOK }}
        run: |
          set -euo pipefail
          echo "Triggering Render deploy hook for Celery worker..."
          curl --fail --show-error --silent -X POST "$RENDER_CELERY_DEPLOY_HOOK"

      - name: Log manual dispatch reason
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.reason != ''
        run: echo "Manual deploy reason: ${{ github.event.inputs.reason }}"
